import Foundation

public struct SubtitleCue: Identifiable, Codable, Hashable {
    public let id: UUID
    public let startTime: TimeInterval
    public let endTime: TimeInterval
    public let text: String

    public init(id: UUID = UUID(), startTime: TimeInterval, endTime: TimeInterval, text: String) {
        self.id = id
        self.startTime = startTime
        self.endTime = endTime
        self.text = text
    }
}

public struct SubtitleTrack: Identifiable, Codable, Hashable {
    public let id: String
    public let language: String
    public let label: String
    public let url: URL
    public let isAutoGenerated: Bool

    public init(id: String = UUID().uuidString, language: String, label: String, url: URL, isAutoGenerated: Bool = false) {
        self.id = id
        self.language = language
        self.label = label
        self.url = url
        self.isAutoGenerated = isAutoGenerated
    }
}
